#!/bin/sh

sxhkd &
panel &
compton & 

bspc monitor -d WEB DEV CHAT NULL

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a chromium desktop='^1'
bspc rule -a mpv desktop='^4'
